/** Every user-facing string. Standard written Chinese, Hong Kong usage. */
export const STRINGS = Object.freeze({
  appTitle: '倉頡練習',
  subtitle: '以倉頡輸入法練習香港書面語及粵語最常用的字',

  setName: (n: number) => `第 ${n} 組`,
  setRange: (from: number, to: number) => `第 ${from} 至 ${to} 字`,
  bestLabel: '最佳',
  noBest: '—',
  timed: '計時',
  free: '自由練習',

  scramble: '打亂次序',
  restart: '重新開始',
  back: '返回',
  hint: '請切換至倉頡輸入法',
  placeholder: '在此輸入',
  inputLabel: '請輸入上方顯示的字',
  done: '完成',
  pause: '暫停',
  resume: '繼續',
  paused: '已暫停',

  setComplete: (n: number) => `第 ${n} 組完成`,
  charsPerMinute: '每分鐘字數',
  accuracy: '準確度',
  time: '時間',
  record: '紀錄',
  newBest: '新紀錄',
  best: (time: string) => `最佳 ${time}`,
  noRecord: '未有紀錄',
  missed: '錯字',
  noMistakes: '全部正確',
  retry: '再試一次',
  retryScrambled: '打亂再試',
  backToSets: '返回字組',
})
