#!/usr/bin/env node
/**
 * Regenerates src/data/cangjie.ts: the third-generation Cangjie code for
 * every character in src/data/sets.ts, taken from the Unicode Unihan
 * database (field kCangjie).
 *
 * Usage: npm run build:cangjie   (also run by npm run build:characters)
 * The Unihan zip and the extracted text file are cached in data-sources/
 * (git-ignored). Delete both to pick up a new Unihan release.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DATA_DIR = join(ROOT, 'data-sources')
const SETS_FILE = join(ROOT, 'src', 'data', 'sets.ts')
const OUTPUT = join(ROOT, 'src', 'data', 'cangjie.ts')

const UNIHAN_URL = 'https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip'
const UNIHAN_FILE = 'Unihan_DictionaryLikeData.txt'

function fail(message) {
  console.error(`build-cangjie: ${message}`)
  process.exit(1)
}

async function download(url, dest) {
  if (existsSync(dest)) return
  console.log(`downloading ${url}`)
  const res = await fetch(url)
  if (!res.ok) fail(`download failed: ${res.status} ${res.statusText} for ${url}`)
  writeFileSync(dest, Buffer.from(await res.arrayBuffer()))
}

/** The set characters, in order, read from the ten string literals in sets.ts. */
function readSetCharacters() {
  const source = readFileSync(SETS_FILE, 'utf8')
  const literals = [...source.matchAll(/'([^']+)'/g)].map((m) => m[1])
  const chars = [...literals.join('')]
  if (chars.length !== 1000) fail(`expected 1000 characters in sets.ts, found ${chars.length}`)
  return chars
}

/** Character -> kCangjie code for every entry in the Unihan file. */
function parseUnihan(text) {
  const codes = new Map()
  for (const line of text.split('\n')) {
    const m = line.match(/^U\+([0-9A-F]+)\tkCangjie\t([A-Z]+)\s*$/)
    if (m) codes.set(String.fromCodePoint(parseInt(m[1], 16)), m[2])
  }
  return codes
}

function render(entries) {
  const lines = entries.map(([ch, code]) => `  '${ch}': '${code}',`)
  return `/**
 * Third-generation Cangjie codes for every character in sets.ts.
 * Generated by scripts/build-cangjie.mjs; do not edit by hand.
 *
 * Source: Unicode Unihan database, field kCangjie, © Unicode, Inc.,
 * used under the Unicode License v3, https://www.unicode.org/license.txt
 */
export const CANGJIE: Readonly<Record<string, string>> = Object.freeze({
${lines.join('\n')}
})
`
}

async function main() {
  mkdirSync(DATA_DIR, { recursive: true })
  const zip = join(DATA_DIR, 'Unihan.zip')
  const txt = join(DATA_DIR, UNIHAN_FILE)
  await download(UNIHAN_URL, zip)
  if (!existsSync(txt)) execFileSync('unzip', ['-o', '-q', zip, UNIHAN_FILE, '-d', DATA_DIR], { stdio: 'inherit' })

  const codes = parseUnihan(readFileSync(txt, 'utf8'))
  if (codes.size < 20000) fail(`expected at least 20000 kCangjie entries, parsed ${codes.size}`)

  const chars = readSetCharacters()
  const missing = chars.filter((ch) => !codes.has(ch))
  if (missing.length) fail(`no Cangjie code for: ${missing.join('')}`)
  const bad = chars.filter((ch) => !/^[A-Z]{1,5}$/.test(codes.get(ch)))
  if (bad.length) fail(`malformed code for: ${bad.map((ch) => `${ch}=${codes.get(ch)}`).join(' ')}`)

  const entries = chars.map((ch) => [ch, codes.get(ch)])
  writeFileSync(OUTPUT, render(entries))
  console.log(`wrote ${OUTPUT} with ${entries.length} codes`)
  // Spot check, mirrored by src/data/cangjie.test.ts.
  for (const ch of '嗰草係') console.log(`${ch}: ${codes.get(ch)}`)
}

main()
