export const SET_SIZE = 100
export const SET_COUNT = 10

/**
 * 1000 most frequent characters of Hong Kong written Chinese and spoken
 * Cantonese, most frequent first. Generated by scripts/build-characters.mjs;
 * do not edit by hand.
 *
 * Sources, blended at equal weight (0.5 written, 0.5 spoken)
 * after converting each to per-million character rates:
 *   Written: 八、九十年代香港字頻統計, CUHK Chinese Character Frequency Statistics
 *            for Hong Kong, Mainland China and Taiwan,
 *            https://humanum.arts.cuhk.edu.hk/Lexis/chifreq/
 *   Spoken:  Hong Kong Cantonese Corpus (HKCanCor), Luke & Wong (2015), CC BY 4.0,
 *            https://github.com/fcbond/hkcancor
 * Spoken transcription conventions normalized before counting: 噉→咁, 囖→囉,
 * 𡃉→㗎, 哩→呢, 揾→搵, 吖→呀, 喇→啦, 嚹→喇. The filler transcriptions 喀 and 誒
 * are not counted. Characters outside the Basic Multilingual Plane are excluded.
 */
export const CHARACTERS =
  '係的一我啊咁呢有唔個好你人都啲不佢就是即嗰得嘅㗎會來啦到以在要時大去囉為可樣話多但過嘢又了中上如而同幾出呀冇點家下年之他自知其哋這喎做日覺國咗十成實真乜度能講生後因地對學住嗎所然本意喇也經心作港開睇邊' +
  '喺們方事行果說三最間定和想工子用返己前於者已問頭兩先重外分二俾埋政那小似面跟發天無著哦香法當公應見情或民咪次起理少機買嘞只女主五阿現九道電嗯諗力四解未老食使由文月新高麼種沒書八加看百聽明全與入部錢正些' +
  '及長手至該還身通動信水她讀性陣再平此市場今七表走業題美六千等太相關隻裏嘩仔打難識比咩變將英搵從原第感利常更很計便教份車完氣譬位考叫員張數候啫內代名合晒影萬直死物別每進記受期放落把收回樂亦反士較字特玩司' +
  '選蚊色目聲府望算條制任總議風向細口接認早近體男提處門搞路甚並立試社快化何被活才基帶另光愛海資友金共程白結線報安必論西則半世像啱眼保養改件音界夠產請卻局喂鐘品笑爭始視求鍾單展東權寫交台價非清失科吓建屋整' +
  '持兒決量容商遠花服校差驚區治流賣企式聯各指務元形思神咋轉山版深靚給馬取令魚根星飲幫往言運錯貴越統連費排空觀假傳苦離強號類攞且股濟班許飛需低達易廣格包鬼片紅晚響禮興戲仍梗朋專示唉調角雖支親熱票留院節滿例' +
  '演況底哎步照巴刻管坐醫足李遊案乎房拜續華緊客除姐功消火吃曾歌劇北什造歲約究城切斯故嗱希溫設眾命推銀黑極層質竟否若謂術首投淨告陸它集林味奇顯黨委義談查咦零態街皮歡飯據段團喜夜辦齊古繼南廿師願克耐官典境翻' +
  '引舊初際套青停肯組病派舉驗讓絕傷盡換牌怎婚環值旅樓終紙裝增般唧羅準象周輕尾升料型筆參灣精壓怪導景碼吔短倒辛職唱沙衣獨陽顧息素存黃斷標居隊傾證球級亞趣軍媽語肉圖腦勢預爾免確待句拍突洲育跑貨堂致茶習京具領' +
  '店印龍須擔減腳歷牛康隨策退肥雙責找拉藝剪福餐普陳德冷劃怕紀圍血誰供站拿備益布警超席賺夫討適製創署聞負碟豐項止痛戰吸頓富慘慮孩稱答哥注石器嚴熟朝架久靜着核殺章效維酒送木介譯研呃律護勞施洋波錄吧遲狗批掂背' +
  '草永跳技米洗慢漸樹規款楚破課獲稅亂壞估屬燈助園某髮聖率母簡追途訂郵膚雨修毛擺史鐵婆葉構評購控儲念限左系露登油牙透廠煩群頂依括搭衰匯承雀佬曲煙蘭抵彩忽罪麻愈售害密館革營彈雜骨補疑休督王奶採舞借隔袋缺船澳' +
  '玲靈協威卡餘尼充塊私犀付庭藥端跌財置慣畫江韓揀微探善彭積模納穿測雲烈懷宣呼郭額釋閒秘紫急菜犯惡寄悶春封均敢醒室琴杯妹租秋副列季舒勝省臨歸尤監迷移散訴良擇乾覆勁豬午競歐土紹啟床莫訪異淡招座執速默畢父避里'

const all = [...CHARACTERS]

export const SETS: string[][] = Array.from({ length: SET_COUNT }, (_, i) =>
  all.slice(i * SET_SIZE, (i + 1) * SET_SIZE),
)
