export const SET_SIZE = 100
export const SET_COUNT = 10

/**
 * 1000 most frequent characters of Hong Kong written Chinese and spoken
 * Cantonese, most frequent first. Generated by scripts/build-characters.mjs;
 * do not edit by hand.
 *
 * Sources, blended at equal weight (0.5 written, 0.5 spoken)
 * after converting each to per-million character rates:
 *   Written: 八、九十年代香港字頻統計, CUHK Chinese Character Frequency Statistics
 *            for Hong Kong, Mainland China and Taiwan,
 *            https://humanum.arts.cuhk.edu.hk/Lexis/chifreq/
 *   Spoken:  Hong Kong Cantonese Corpus (HKCanCor), Luke & Wong (2015), CC BY 4.0,
 *            https://github.com/fcbond/hkcancor
 * Spoken transcription variants normalized before counting: 噉→咁, 囖→囉, 𡃉→㗎.
 * Characters outside the Basic Multilingual Plane are excluded.
 */
export const CHARACTERS =
  '係的一我啊咁有唔個好你人呢都啲不佢就是即嗰得嘅㗎會來喇到以在要時大去囉為可樣話多但過嘢了又中上如而同幾出冇點家年下他之哩自這知其哋喎做國日覺咗十成實誒真乜度能生後講因地對學住嗎所喀然本意也嚹心經吖作港' +
  '開邊睇喺們方事行說果三最間定和想工子用己返前於者已問頭兩先外分重二政俾那埋小似面發跟天無著香法當哦公應見情民或次起咪理機少呀買只嘞女主五阿現九道電嗯諗力四解未老使食由文月新高麼種沒書加看八百明聽全與入' +
  '部正錢些及長手至該還身動通信水她性讀再此平陣市場今七表走業題美六千等太相關裏隻嘩打難仔比識變將咩英從原感第利常更很揾計便教份車氣完位譬考員叫張數候內啫代名合晒影萬直死物別每進受記期放把落收回樂亦反士較' +
  '特字玩司選色目府聲蚊望算制條任總議風向口細接認早近體男提處門搞路甚並立社試快化何被才活基光帶另愛海資友共金程白結線安報必則論西世像半眼啱保改養件音界夠產請卻局品笑爭喂鐘始視求單展東權鍾寫交台非價清失建' +
  '科吓屋整持兒決量容商花遠服校差區驚治流式聯賣企各指元務形思神山咋轉深版給取馬靚令魚往根星飲言幫運統錯越連費貴排空觀假傳苦強離類且號攞濟許股班飛需達低易廣格包片紅鬼響晚興仍戲禮朋示梗專調角雖唉支親熱票留' +
  '院滿節例演況底步照巴刻哎管坐足醫李案遊乎房續拜華緊客除姐功消吃火曾劇北歌什造歲約切究斯城故希溫設眾命嗱推銀黑極層否質竟若術首投謂它告陸淨集林味奇顯黨委義談查態零咦街皮歡據飯喜段團夜辦古齊繼南師願廿克官' +
  '境耐引典翻際舊初青套組病派停肯舉驗讓絕傷盡怎換牌婚環值樓終紙裝旅增般羅唧準象輕周升料筆參型尾灣精壓怪導景碼倒職短吔衣辛唱沙獨陽顧息素存黃斷標居隊證球級傾亞軍趣媽語圖肉腦勢免預確爾待句育拍突洲跑貨堂致習' +
  '茶京具領店印須擔減龍歷腳康隨策牛退雙責肥找拉藝福剪餐普陳德劃怕冷紀圍血誰供站拿備益布警超席夫討適賺製署創聞負豐項戰止痛碟吸頓富慘孩慮稱答注石器嚴久哥熟靜朝架核殺着效章維酒送木研介律護譯呃勞施洋吧波錄批' +
  '背草永遲狗技跳掂米漸洗樹慢規款楚破獲課稅亂壞屬燈助估園某髮率母簡膚雨追修途訂聖毛史郵擺鐵葉婆構評購控念限儲左系露登油牙透廠群煩依頂括匯承搭曲煙衰雀佬蘭抵彩忽愈售罪害密館麻革營彈雜骨疑休督補王採舞奶借隔' +
  '缺船袋澳玲協靈威餘卡尼充塊私付庭藥財端置跌犀慣畫江韓微探揀善彭積模納穿測雲烈懷宣呼郭額釋閒紫秘急菜犯春惡寄悶均封敢醒室琴秋副杯列季妹租勝省舒臨歸尤監迷移散訴良擇乾午覆競歐勁土豬啟床莫訪異紹淡招座執速默'

const all = [...CHARACTERS]

export const SETS: string[][] = Array.from({ length: SET_COUNT }, (_, i) =>
  all.slice(i * SET_SIZE, (i + 1) * SET_SIZE),
)
